### ISSUE TITLE
Parts evaluation input enhancements

### ISSUE THREAD

**Issue by CasperNaudts** [Edu-Tech-Group/cloudclass-roadmap#31]
- Date range
- Horizontal grading at once

Heavy item due to 
- https://github.com/HoudiniGraphql/houdini/issues/1143

**Comment by CasperNaudts** [comment]
PR made for fix in library
- https://github.com/HoudiniGraphql/houdini/pull/1253

**Comment by SeppahBaws** [comment]
2nd blocker has a work-in-progress fix in the library
- https://github.com/HoudiniGraphql/houdini/pull/1145
